GroceryHome/Areas/DieuHanh/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryHome.Models;
using GroceryHome.Areas.DieuHanh.Models;

namespace GroceryHome.Areas.DieuHanh.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: DieuHanh/Home
        public ActionResult Index()
        {
            //if (!string.IsNullOrEmpty(Request["userName"]) && !string.IsNullOrEmpty(Request["passWord"]))
            //{
            //    return View();
            //}
            if (LoginSatus.IsloginAdmin == true)
            {
                return View();
            }
            return RedirectToAction("Login", "Login");
        }
    }
}

GroceryHome/Areas/DieuHanh/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryHome.Models;

namespace GroceryHome.Areas.DieuHanh.Controllers
{
    public class QuanLyDonHangController : Controller
    {

        private readonly GroceryHomeEntities dB = new GroceryHomeEntities();
        // GET: DieuHanh/QuanLyDonHang
        public ActionResult Index()
        {
            if (Session["CurrentUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            List<tbl_DatHang> ListDatHang = new List<tbl_DatHang>();
            try
            {
                ListDatHang = dB.tbl_DatHang.Where(d => d.IsDelete == false).ToList();
            }
            catch
            {


            }
            return View(ListDatHang);
        }

        public ActionResult DetailsDonHang(string id)
        {
            Guid Id = new Guid(id);
            ViewBag.IdDonHang = id;
            var IdGioHang = dB.tbl_DatHang.Find(Id).IdGioHang;
            var listSanPham = dB.tbl_GioHang_SanPham.Where(d => d.IdGioHang == IdGioHang && d.IsDelete == 0).ToList();
            var models = new List<DetailsDonHang>();
            foreach (var item in listSanPham)
            {
                if (models.Any(d => d.IdSanPham == item.IdSanPham))
                {
                    models.Where(d => d.IdSanPham == item.IdSanPham).FirstOrDefault().SoLuong += item.SoLuong;
                }
                else
                {
                    var SP = new DetailsDonHang();
                    SP.Id = item.Id;
                    SP.IdGioHang = item.IdGioHang;
                    SP.IdSanPham = item.IdSanPham;
                    SP.SoLuong = item.SoLuong;
                    SP.SoLuongConLai = dB.tbl_SanPham.Find(item.IdSanPham).SoLuongConLai;
                    SP.DonGia = item.DonGia;
                    SP.ThanhTien = item.ThanhTien;
                    SP.TenSP = item.TenSP;
                    SP.NgayThem = item.NgayThem;
                    SP.IsDelete = item.IsDelete;
                    SP.Note = item.Note;
                    models.Add(SP);
                }
            }
            return View(models);
        }

        public void ConfirmDonHang(string id, string status)
        {
            Guid Id = new Guid(id);
            var donHang = dB.tbl_DatHang.Find(Id);
            var SPGioHang = dB.tbl_GioHang_SanPham.Where(d => d.IdGioHang == donHang.IdGioHang).ToList();
            var checkStatus = false;
            foreach (var item in SPGioHang)
            {
                var SP = dB.tbl_SanPham.Find(item.IdSanPham);
                if (item.SoLuong <= SP.SoLuongConLai)
                {
                    SP.SoLuongConLai -= item.SoLuong;
                    item.Note = "Đang chuẩn bị";
                    item.IsAccept = 1;
                    checkStatus = true;                  
                }
                else
                {
                    item.IsAccept = 2;
                    donHang.TongHoaDon -= item.ThanhTien;
                    item.ThanhTien = 0;
                    item.Note = "Hết hàng";
                    donHang.AdminFeedback += item.TenSP + " không đủ hàng" + "\r\n";
                }
                dB.SaveChanges();
            }
            if (checkStatus)
            {
                donHang.Status = 1;
            }
            else
            {
                donHang.Status = 2;
            }
            dB.SaveChanges();
        }

        public void RejectDonHang(string id, string status)
        {
            Guid Id = new Guid(id);
            var donHang = dB.tbl_DatHang.Find(Id);
            donHang.Status = 2;
            dB.SaveChanges();
        }

        public ActionResult DonChoDuyet()
        {
            if (Session["CurrentUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            List<tbl_DatHang> ListDatHang = new List<tbl_DatHang>();
            try
            {
                ListDatHang = dB.tbl_DatHang.Where(d => d.IsDelete == false && d.Status == 0).ToList();
            }
            catch
            {


            }
            return View(ListDatHang);
        }

        public ActionResult DonDaHuy()
        {
            if (Session["CurrentUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            List<tbl_DatHang> ListDatHang = new List<tbl_DatHang>();
            try
            {
                ListDatHang = dB.tbl_DatHang.Where(d => d.IsDelete == false && d.Status == 2).ToList();
            }
            catch
            {


            }
            return View(ListDatHang);

        }

        public ActionResult DaXacNhan()
        {
            if (Session["CurrentUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            List<tbl_DatHang> ListDatHang = new List<tbl_DatHang>();
            try
            {
                ListDatHang = dB.tbl_DatHang.Where(d => d.IsDelete == false && d.Status ==1).ToList();
            }
            catch
            {


            }
            return View(ListDatHang);
        }
    }
}

GroceryHome/Areas/DieuHanh/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.MemoryMappedFiles;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using GroceryHome.Areas.DieuHanh.Models;
namespace GroceryHome.Areas.DieuHanh.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        private readonly GroceryHomeEntities dB = new GroceryHomeEntities();
        // GET: DieuHanh/QuanLySanPham
        public ActionResult Index(string TenSP, string LoaiSP)
        {
            int loaiSP;
            Int32.TryParse(LoaiSP, out loaiSP);
            var models = new List<tbl_SanPham>();
            if (!LoginSatus.IsloginAdmin)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {              
                if (dB.tbl_SanPham.Any(d=>d.Id != 0))
                {
                    models = dB.tbl_SanPham.Where(d => d.Id != 0).ToList();
                    if (loaiSP != 0)
                    {
                        models = models.Where(d => d.LoaiSP == loaiSP).ToList();
                    }
                    if (!string.IsNullOrEmpty(TenSP))
                    {
                        models = models.Where(d => d.TenSP == TenSP).ToList();
                    }
                }
            }
            return View(models);
        }

        public ActionResult ThemMoiSP(SanPham model)
        {
            if (!LoginSatus.IsloginAdmin)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (Request.HttpMethod == "POST")
                {
                    try
                    {
                        if (model.LoaiSP == 0)
                        {

                        }
                        if (model.ImageFile != null)
                        {
                            string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                            string fileExtension = Path.GetExtension(model.ImageFile.FileName);
                            string uploadPath = ConfigurationManager.AppSettings["ProductPath"].ToString();
                            model.ImagePath = uploadPath + fileName + fileExtension;
                            model.ImageFile.SaveAs(model.ImagePath);
                        }
                        tbl_SanPham addSanPham = new tbl_SanPham();
                        addSanPham.TenSP = model.TenSP;
                        addSanPham.LoaiSP = model.LoaiSP;
                        addSanPham.Mota = model.Mota;
                        addSanPham.Gia = model.Gia;
                        addSanPham.Hinh = model.ImageFile.FileName;
                        dB.tbl_SanPham.Add(addSanPham);
                        dB.SaveChanges();
                    }
                    catch { }

                }
                return View();
            }
        }

        public ActionResult CapNhatSP(SanPham updateSP, string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                int Id = Convert.ToInt32(id);
                var model = dB.tbl_SanPham.Find(Id);
                if (Request.HttpMethod == "POST")
                {
                    model.TenSP = updateSP.TenSP;
                    model.LoaiSP = updateSP.LoaiSP;
                    model.Mota = updateSP.Mota;
                    model.Gia = updateSP.Gia;
                    string path = ConfigurationManager.AppSettings["ProductPath"].ToString();

                    if (updateSP.ImageFile!=null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(updateSP.ImageFile.FileName);
                        string fileExtension = Path.GetExtension(updateSP.ImageFile.FileName);
                        string uploadPath = ConfigurationManager.AppSettings["ProductPath"].ToString();
                        updateSP.ImagePath = uploadPath + fileName + fileExtension;
                        updateSP.ImageFile.SaveAs(updateSP.ImagePath);
                        model.Hinh = updateSP.ImageFile.FileName;                        
                    }
                    dB.SaveChanges();
                    return RedirectToAction("Index");
                }
                updateSP.Id = Convert.ToInt32(model.Id);
                updateSP.TenSP = model.TenSP;
                updateSP.LoaiSP = model.LoaiSP;
                updateSP.Mota = model.Mota;
                updateSP.Gia = Convert.ToDecimal(model.Gia);
                updateSP.FileName = model.Hinh;
                return View(updateSP);
            }
            return View("Index");
        }

        public ActionResult XoaSP(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                int Id = Convert.ToInt32(id);
                var model = dB.tbl_SanPham.Find(Id);
                dB.tbl_SanPham.Remove(model);
                dB.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public void Xoa(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                int Id = Convert.ToInt32(id);
                var model = dB.tbl_SanPham.Find(Id);
                dB.tbl_SanPham.Remove(model);
                dB.SaveChanges();
            }
        }

        public ActionResult ThemLoaiSP(SanPham sanPham)
        {
            if (!string.IsNullOrEmpty(sanPham.LoaiSPMoi)) 
            {
                tbl_LoaiSanPham newLoaiSP = new tbl_LoaiSanPham();
                newLoaiSP.LoaiSP = sanPham.LoaiSPMoi;
                dB.tbl_LoaiSanPham.Add(newLoaiSP);
                dB.SaveChanges();
            }
            return View("ThemMoiSP");
        }
    }
}

GroceryHome/Areas/DieuHanh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản trị - @ViewBag.Title - Grocery Home</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <style>
        .dropbtn {
            padding: 16px;
            font-size: 14px;
            border: none;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;            
            color: #999;
            background-color:#222;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            min-width: 170px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            background-color:#faf1f1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #ddd;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            color:white;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Grocery Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "AdminHome")</li>
                    <div class="dropdown">
                        <button class="dropbtn">Quản lý đơn hàng</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Đơn chờ duyệt", "DonChoDuyet", "QuanLyDonHang")
                            @Html.ActionLink("Đã xác nhận", "DaXacNhan", "QuanLyDonHang")
                            @Html.ActionLink("Đơn đã hủy", "DonDaHuy", "QuanLyDonHang")
                        </div>
                    </div>
                    <div class="dropdown">
                        <button class="dropbtn">Quản lý sản phẩm</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Danh sách sản phẩm", "Index", "QuanLySanPham")
                            @Html.ActionLink("Thêm sản phẩm mới", "ThemMoiSP", "QuanLySanPham")
                        </div>
                    </div>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>